
services:
    # server:
    #   build:
    #     context: .
    #     target: development
    #   restart: always
    #   depends_on:
    #     - postgres
    #   ports:
    #     - 3000:3000
    #   env_file:
    #     - .env

    #   # establish docker compose watch mode for the api service
    #   develop:
    #     # specify the files to watch for changes
    #     watch:
    #       # it'll watch for changes in package.json and package-lock.json and rebuild the container and image if there are any changes
    #       - path: ./package.json
    #         action: rebuild
    #       - path: ./package-lock.json
    #         action: rebuild

    #       # it'll watch for changes in the backend directory and sync the changes with the container real time
    #       - path: ./app
    #         target: /app
    #         action: sync

    postgres:
        image: postgres
        hostname: localhost
        restart: always
        shm_size: 128mb
        volumes:
        - pg-data:/var/lib/postgresql
        ports:
        - 5432:5432  # make sure you don't have another container running on 5432

        environment:
        - POSTGRES_DB=one-piece-db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin


    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - redis-data:/data

volumes:
    redis-data:
    pg-data:
