export const toastKey = "toast";
export const SESSION_EXPIRATION_TIME = 1000 * 60 * 60 * 24 * 30;
export const providerIdKey = "providerId";
export const sessionKey = "sessionId";
export const prefilledProfileKey = "prefilledProfile";
export const onboardingEmailSessionKey = "onboardingEmail";
export const resetPasswordUsernameSessionKey = "resetPasswordUsername";
export const unverifiedSessionIdKey = "unverified-session-id";
export const verifiedTimeKey = "verified-time";
export const rememberKey = "remember";
export const profileUpdateActionIntent = "update-profile";
export const signOutOfSessionsActionIntent = "sign-out-of-sessions";
export const placeholderAvatar =
  "https://api.dicebear.com/9.x/adventurer/svg?seed=Oliver";
// export const placeholderAvatar = '/placeholder.jpg'
